game.window.width=1280
game.window.height=1024
game.animation.tank-speed=0.4
game.animation.bullet-speed=0.1
game.animation.tree-speed=0.0
game.controller.random.fire-probability=0.15
game.tank.max-health=100
game.bullet.damage=25
